load("@rules_cc//cc:defs.bzl", "cc_binary")

package(default_applicable_licenses = ["//third_party/bazel_rules/rules_proto:license"])

cc_binary(
    name = "file_concat",
    srcs = [
        "main.cc",
    ],
    visibility = ["//visibility:public"],
)
