load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

bzl_library(
    name = "proto_common",
    srcs = [
        "proto_common.bzl",
        "proto_info.bzl",
        "proto_lang_toolchain_info.bzl",
    ],
    visibility = ["//visibility:public"],
)
