load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

# Intentionally left empty (for now).

bzl_library(
    name = "dependencies",
    srcs = ["dependencies.bzl"],
)

bzl_library(
    name = "native",
    srcs = ["native.bzl"],
)
