load("//proto:defs.bzl", "proto_library")

package(default_applicable_licenses = ["//third_party/bazel_rules/rules_proto:license"])

proto_library(
    name = "empty_proto",
    srcs = [
        "empty.proto",
    ],
)
