load("//tests/analysis:proto_common_contains_native_fields_test.bzl", "proto_common_contains_native_fields_test")

proto_common_contains_native_fields_test(
    name = "proto_common_contains_native_fields_test",
)
