load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "workspace_constants",
    testonly = True,
    hdrs = [
        "workspace_constants.h",
    ],
    visibility = [
        "//tests:__subpackages__",
    ],
)
